// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/NpoolPlatform/user-management/pkg/db/ent/schema"
	"github.com/NpoolPlatform/user-management/pkg/db/ent/user"
	"github.com/NpoolPlatform/user-management/pkg/db/ent/userfrozen"
	"github.com/NpoolPlatform/user-management/pkg/db/ent/userprovider"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescDisplayName is the schema descriptor for display_name field.
	userDescDisplayName := userFields[4].Descriptor()
	// user.DefaultDisplayName holds the default value on creation for the display_name field.
	user.DefaultDisplayName = userDescDisplayName.Default.(string)
	// userDescCreateAt is the schema descriptor for create_at field.
	userDescCreateAt := userFields[8].Descriptor()
	// user.DefaultCreateAt holds the default value on creation for the create_at field.
	user.DefaultCreateAt = userDescCreateAt.Default.(func() uint32)
	// userDescUpdateAt is the schema descriptor for update_at field.
	userDescUpdateAt := userFields[9].Descriptor()
	// user.DefaultUpdateAt holds the default value on creation for the update_at field.
	user.DefaultUpdateAt = userDescUpdateAt.Default.(func() uint32)
	// user.UpdateDefaultUpdateAt holds the default value on update for the update_at field.
	user.UpdateDefaultUpdateAt = userDescUpdateAt.UpdateDefault.(func() uint32)
	// userDescDeleteAt is the schema descriptor for delete_at field.
	userDescDeleteAt := userFields[10].Descriptor()
	// user.DefaultDeleteAt holds the default value on creation for the delete_at field.
	user.DefaultDeleteAt = userDescDeleteAt.Default.(func() uint32)
	// userDescAvatar is the schema descriptor for avatar field.
	userDescAvatar := userFields[11].Descriptor()
	// user.DefaultAvatar holds the default value on creation for the avatar field.
	user.DefaultAvatar = userDescAvatar.Default.(string)
	// userDescRegion is the schema descriptor for region field.
	userDescRegion := userFields[12].Descriptor()
	// user.DefaultRegion holds the default value on creation for the region field.
	user.DefaultRegion = userDescRegion.Default.(string)
	// userDescAge is the schema descriptor for age field.
	userDescAge := userFields[13].Descriptor()
	// user.DefaultAge holds the default value on creation for the age field.
	user.DefaultAge = userDescAge.Default.(uint32)
	// userDescGender is the schema descriptor for gender field.
	userDescGender := userFields[14].Descriptor()
	// user.DefaultGender holds the default value on creation for the gender field.
	user.DefaultGender = userDescGender.Default.(string)
	// userDescBirthday is the schema descriptor for birthday field.
	userDescBirthday := userFields[15].Descriptor()
	// user.DefaultBirthday holds the default value on creation for the birthday field.
	user.DefaultBirthday = userDescBirthday.Default.(string)
	// userDescCountry is the schema descriptor for country field.
	userDescCountry := userFields[16].Descriptor()
	// user.DefaultCountry holds the default value on creation for the country field.
	user.DefaultCountry = userDescCountry.Default.(string)
	// userDescProvince is the schema descriptor for province field.
	userDescProvince := userFields[17].Descriptor()
	// user.DefaultProvince holds the default value on creation for the province field.
	user.DefaultProvince = userDescProvince.Default.(string)
	// userDescCity is the schema descriptor for city field.
	userDescCity := userFields[18].Descriptor()
	// user.DefaultCity holds the default value on creation for the city field.
	user.DefaultCity = userDescCity.Default.(string)
	// userDescCareer is the schema descriptor for career field.
	userDescCareer := userFields[19].Descriptor()
	// user.DefaultCareer holds the default value on creation for the career field.
	user.DefaultCareer = userDescCareer.Default.(string)
	// userDescFirstName is the schema descriptor for first_name field.
	userDescFirstName := userFields[20].Descriptor()
	// user.DefaultFirstName holds the default value on creation for the first_name field.
	user.DefaultFirstName = userDescFirstName.Default.(string)
	// userDescLastName is the schema descriptor for last_name field.
	userDescLastName := userFields[21].Descriptor()
	// user.DefaultLastName holds the default value on creation for the last_name field.
	user.DefaultLastName = userDescLastName.Default.(string)
	// userDescStreetAddress1 is the schema descriptor for street_address1 field.
	userDescStreetAddress1 := userFields[22].Descriptor()
	// user.DefaultStreetAddress1 holds the default value on creation for the street_address1 field.
	user.DefaultStreetAddress1 = userDescStreetAddress1.Default.(string)
	// userDescStreetAddress2 is the schema descriptor for street_address2 field.
	userDescStreetAddress2 := userFields[23].Descriptor()
	// user.DefaultStreetAddress2 holds the default value on creation for the street_address2 field.
	user.DefaultStreetAddress2 = userDescStreetAddress2.Default.(string)
	// userDescCompony is the schema descriptor for compony field.
	userDescCompony := userFields[24].Descriptor()
	// user.DefaultCompony holds the default value on creation for the compony field.
	user.DefaultCompony = userDescCompony.Default.(string)
	// userDescPostalCode is the schema descriptor for postal_code field.
	userDescPostalCode := userFields[25].Descriptor()
	// user.DefaultPostalCode holds the default value on creation for the postal_code field.
	user.DefaultPostalCode = userDescPostalCode.Default.(string)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	userfrozenFields := schema.UserFrozen{}.Fields()
	_ = userfrozenFields
	// userfrozenDescCreateAt is the schema descriptor for create_at field.
	userfrozenDescCreateAt := userfrozenFields[4].Descriptor()
	// userfrozen.DefaultCreateAt holds the default value on creation for the create_at field.
	userfrozen.DefaultCreateAt = userfrozenDescCreateAt.Default.(func() uint32)
	// userfrozenDescEndAt is the schema descriptor for end_at field.
	userfrozenDescEndAt := userfrozenFields[5].Descriptor()
	// userfrozen.DefaultEndAt holds the default value on creation for the end_at field.
	userfrozen.DefaultEndAt = userfrozenDescEndAt.Default.(uint32)
	// userfrozenDescID is the schema descriptor for id field.
	userfrozenDescID := userfrozenFields[0].Descriptor()
	// userfrozen.DefaultID holds the default value on creation for the id field.
	userfrozen.DefaultID = userfrozenDescID.Default.(func() uuid.UUID)
	userproviderFields := schema.UserProvider{}.Fields()
	_ = userproviderFields
	// userproviderDescCreateAt is the schema descriptor for create_at field.
	userproviderDescCreateAt := userproviderFields[5].Descriptor()
	// userprovider.DefaultCreateAt holds the default value on creation for the create_at field.
	userprovider.DefaultCreateAt = userproviderDescCreateAt.Default.(func() uint32)
	// userproviderDescUpdateAt is the schema descriptor for update_at field.
	userproviderDescUpdateAt := userproviderFields[6].Descriptor()
	// userprovider.DefaultUpdateAt holds the default value on creation for the update_at field.
	userprovider.DefaultUpdateAt = userproviderDescUpdateAt.Default.(func() uint32)
	// userprovider.UpdateDefaultUpdateAt holds the default value on update for the update_at field.
	userprovider.UpdateDefaultUpdateAt = userproviderDescUpdateAt.UpdateDefault.(func() uint32)
	// userproviderDescDeleteAt is the schema descriptor for delete_at field.
	userproviderDescDeleteAt := userproviderFields[7].Descriptor()
	// userprovider.DefaultDeleteAt holds the default value on creation for the delete_at field.
	userprovider.DefaultDeleteAt = userproviderDescDeleteAt.Default.(func() uint32)
	// userproviderDescID is the schema descriptor for id field.
	userproviderDescID := userproviderFields[0].Descriptor()
	// userprovider.DefaultID holds the default value on creation for the id field.
	userprovider.DefaultID = userproviderDescID.Default.(func() uuid.UUID)
}
