// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/user-management/pkg/db/ent/userfrozen"
	"github.com/google/uuid"
)

// UserFrozenCreate is the builder for creating a UserFrozen entity.
type UserFrozenCreate struct {
	config
	mutation *UserFrozenMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (ufc *UserFrozenCreate) SetUserID(u uuid.UUID) *UserFrozenCreate {
	ufc.mutation.SetUserID(u)
	return ufc
}

// SetFrozenBy sets the "frozen_by" field.
func (ufc *UserFrozenCreate) SetFrozenBy(u uuid.UUID) *UserFrozenCreate {
	ufc.mutation.SetFrozenBy(u)
	return ufc
}

// SetFrozenCause sets the "frozen_cause" field.
func (ufc *UserFrozenCreate) SetFrozenCause(s string) *UserFrozenCreate {
	ufc.mutation.SetFrozenCause(s)
	return ufc
}

// SetCreateAt sets the "create_at" field.
func (ufc *UserFrozenCreate) SetCreateAt(u uint32) *UserFrozenCreate {
	ufc.mutation.SetCreateAt(u)
	return ufc
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (ufc *UserFrozenCreate) SetNillableCreateAt(u *uint32) *UserFrozenCreate {
	if u != nil {
		ufc.SetCreateAt(*u)
	}
	return ufc
}

// SetEndAt sets the "end_at" field.
func (ufc *UserFrozenCreate) SetEndAt(u uint32) *UserFrozenCreate {
	ufc.mutation.SetEndAt(u)
	return ufc
}

// SetNillableEndAt sets the "end_at" field if the given value is not nil.
func (ufc *UserFrozenCreate) SetNillableEndAt(u *uint32) *UserFrozenCreate {
	if u != nil {
		ufc.SetEndAt(*u)
	}
	return ufc
}

// SetStatus sets the "status" field.
func (ufc *UserFrozenCreate) SetStatus(s string) *UserFrozenCreate {
	ufc.mutation.SetStatus(s)
	return ufc
}

// SetUnfrozenBy sets the "unfrozen_by" field.
func (ufc *UserFrozenCreate) SetUnfrozenBy(u uuid.UUID) *UserFrozenCreate {
	ufc.mutation.SetUnfrozenBy(u)
	return ufc
}

// SetID sets the "id" field.
func (ufc *UserFrozenCreate) SetID(u uuid.UUID) *UserFrozenCreate {
	ufc.mutation.SetID(u)
	return ufc
}

// Mutation returns the UserFrozenMutation object of the builder.
func (ufc *UserFrozenCreate) Mutation() *UserFrozenMutation {
	return ufc.mutation
}

// Save creates the UserFrozen in the database.
func (ufc *UserFrozenCreate) Save(ctx context.Context) (*UserFrozen, error) {
	var (
		err  error
		node *UserFrozen
	)
	ufc.defaults()
	if len(ufc.hooks) == 0 {
		if err = ufc.check(); err != nil {
			return nil, err
		}
		node, err = ufc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserFrozenMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ufc.check(); err != nil {
				return nil, err
			}
			ufc.mutation = mutation
			if node, err = ufc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(ufc.hooks) - 1; i >= 0; i-- {
			if ufc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ufc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ufc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ufc *UserFrozenCreate) SaveX(ctx context.Context) *UserFrozen {
	v, err := ufc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ufc *UserFrozenCreate) Exec(ctx context.Context) error {
	_, err := ufc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ufc *UserFrozenCreate) ExecX(ctx context.Context) {
	if err := ufc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ufc *UserFrozenCreate) defaults() {
	if _, ok := ufc.mutation.CreateAt(); !ok {
		v := userfrozen.DefaultCreateAt()
		ufc.mutation.SetCreateAt(v)
	}
	if _, ok := ufc.mutation.EndAt(); !ok {
		v := userfrozen.DefaultEndAt
		ufc.mutation.SetEndAt(v)
	}
	if _, ok := ufc.mutation.ID(); !ok {
		v := userfrozen.DefaultID()
		ufc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ufc *UserFrozenCreate) check() error {
	if _, ok := ufc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "user_id"`)}
	}
	if _, ok := ufc.mutation.FrozenBy(); !ok {
		return &ValidationError{Name: "frozen_by", err: errors.New(`ent: missing required field "frozen_by"`)}
	}
	if _, ok := ufc.mutation.FrozenCause(); !ok {
		return &ValidationError{Name: "frozen_cause", err: errors.New(`ent: missing required field "frozen_cause"`)}
	}
	if _, ok := ufc.mutation.CreateAt(); !ok {
		return &ValidationError{Name: "create_at", err: errors.New(`ent: missing required field "create_at"`)}
	}
	if _, ok := ufc.mutation.EndAt(); !ok {
		return &ValidationError{Name: "end_at", err: errors.New(`ent: missing required field "end_at"`)}
	}
	if _, ok := ufc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "status"`)}
	}
	if _, ok := ufc.mutation.UnfrozenBy(); !ok {
		return &ValidationError{Name: "unfrozen_by", err: errors.New(`ent: missing required field "unfrozen_by"`)}
	}
	return nil
}

func (ufc *UserFrozenCreate) sqlSave(ctx context.Context) (*UserFrozen, error) {
	_node, _spec := ufc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ufc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		_node.ID = _spec.ID.Value.(uuid.UUID)
	}
	return _node, nil
}

func (ufc *UserFrozenCreate) createSpec() (*UserFrozen, *sqlgraph.CreateSpec) {
	var (
		_node = &UserFrozen{config: ufc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: userfrozen.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: userfrozen.FieldID,
			},
		}
	)
	if id, ok := ufc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ufc.mutation.UserID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: userfrozen.FieldUserID,
		})
		_node.UserID = value
	}
	if value, ok := ufc.mutation.FrozenBy(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: userfrozen.FieldFrozenBy,
		})
		_node.FrozenBy = value
	}
	if value, ok := ufc.mutation.FrozenCause(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: userfrozen.FieldFrozenCause,
		})
		_node.FrozenCause = value
	}
	if value, ok := ufc.mutation.CreateAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: userfrozen.FieldCreateAt,
		})
		_node.CreateAt = value
	}
	if value, ok := ufc.mutation.EndAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: userfrozen.FieldEndAt,
		})
		_node.EndAt = value
	}
	if value, ok := ufc.mutation.Status(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: userfrozen.FieldStatus,
		})
		_node.Status = value
	}
	if value, ok := ufc.mutation.UnfrozenBy(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: userfrozen.FieldUnfrozenBy,
		})
		_node.UnfrozenBy = value
	}
	return _node, _spec
}

// UserFrozenCreateBulk is the builder for creating many UserFrozen entities in bulk.
type UserFrozenCreateBulk struct {
	config
	builders []*UserFrozenCreate
}

// Save creates the UserFrozen entities in the database.
func (ufcb *UserFrozenCreateBulk) Save(ctx context.Context) ([]*UserFrozen, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ufcb.builders))
	nodes := make([]*UserFrozen, len(ufcb.builders))
	mutators := make([]Mutator, len(ufcb.builders))
	for i := range ufcb.builders {
		func(i int, root context.Context) {
			builder := ufcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserFrozenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ufcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ufcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ufcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ufcb *UserFrozenCreateBulk) SaveX(ctx context.Context) []*UserFrozen {
	v, err := ufcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ufcb *UserFrozenCreateBulk) Exec(ctx context.Context) error {
	_, err := ufcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ufcb *UserFrozenCreateBulk) ExecX(ctx context.Context) {
	if err := ufcb.Exec(ctx); err != nil {
		panic(err)
	}
}
