// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/user-management/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/user-management/pkg/db/ent/userprovider"
	"github.com/google/uuid"
)

// UserProviderQuery is the builder for querying UserProvider entities.
type UserProviderQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.UserProvider
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserProviderQuery builder.
func (upq *UserProviderQuery) Where(ps ...predicate.UserProvider) *UserProviderQuery {
	upq.predicates = append(upq.predicates, ps...)
	return upq
}

// Limit adds a limit step to the query.
func (upq *UserProviderQuery) Limit(limit int) *UserProviderQuery {
	upq.limit = &limit
	return upq
}

// Offset adds an offset step to the query.
func (upq *UserProviderQuery) Offset(offset int) *UserProviderQuery {
	upq.offset = &offset
	return upq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (upq *UserProviderQuery) Unique(unique bool) *UserProviderQuery {
	upq.unique = &unique
	return upq
}

// Order adds an order step to the query.
func (upq *UserProviderQuery) Order(o ...OrderFunc) *UserProviderQuery {
	upq.order = append(upq.order, o...)
	return upq
}

// First returns the first UserProvider entity from the query.
// Returns a *NotFoundError when no UserProvider was found.
func (upq *UserProviderQuery) First(ctx context.Context) (*UserProvider, error) {
	nodes, err := upq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userprovider.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (upq *UserProviderQuery) FirstX(ctx context.Context) *UserProvider {
	node, err := upq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserProvider ID from the query.
// Returns a *NotFoundError when no UserProvider ID was found.
func (upq *UserProviderQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = upq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{userprovider.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (upq *UserProviderQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := upq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserProvider entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one UserProvider entity is not found.
// Returns a *NotFoundError when no UserProvider entities are found.
func (upq *UserProviderQuery) Only(ctx context.Context) (*UserProvider, error) {
	nodes, err := upq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{userprovider.Label}
	default:
		return nil, &NotSingularError{userprovider.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (upq *UserProviderQuery) OnlyX(ctx context.Context) *UserProvider {
	node, err := upq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserProvider ID in the query.
// Returns a *NotSingularError when exactly one UserProvider ID is not found.
// Returns a *NotFoundError when no entities are found.
func (upq *UserProviderQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = upq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{userprovider.Label}
	default:
		err = &NotSingularError{userprovider.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (upq *UserProviderQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := upq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserProviders.
func (upq *UserProviderQuery) All(ctx context.Context) ([]*UserProvider, error) {
	if err := upq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return upq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (upq *UserProviderQuery) AllX(ctx context.Context) []*UserProvider {
	nodes, err := upq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserProvider IDs.
func (upq *UserProviderQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := upq.Select(userprovider.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (upq *UserProviderQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := upq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (upq *UserProviderQuery) Count(ctx context.Context) (int, error) {
	if err := upq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return upq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (upq *UserProviderQuery) CountX(ctx context.Context) int {
	count, err := upq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (upq *UserProviderQuery) Exist(ctx context.Context) (bool, error) {
	if err := upq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return upq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (upq *UserProviderQuery) ExistX(ctx context.Context) bool {
	exist, err := upq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserProviderQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (upq *UserProviderQuery) Clone() *UserProviderQuery {
	if upq == nil {
		return nil
	}
	return &UserProviderQuery{
		config:     upq.config,
		limit:      upq.limit,
		offset:     upq.offset,
		order:      append([]OrderFunc{}, upq.order...),
		predicates: append([]predicate.UserProvider{}, upq.predicates...),
		// clone intermediate query.
		sql:  upq.sql.Clone(),
		path: upq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserProvider.Query().
//		GroupBy(userprovider.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (upq *UserProviderQuery) GroupBy(field string, fields ...string) *UserProviderGroupBy {
	group := &UserProviderGroupBy{config: upq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := upq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return upq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//	}
//
//	client.UserProvider.Query().
//		Select(userprovider.FieldUserID).
//		Scan(ctx, &v)
//
func (upq *UserProviderQuery) Select(fields ...string) *UserProviderSelect {
	upq.fields = append(upq.fields, fields...)
	return &UserProviderSelect{UserProviderQuery: upq}
}

func (upq *UserProviderQuery) prepareQuery(ctx context.Context) error {
	for _, f := range upq.fields {
		if !userprovider.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if upq.path != nil {
		prev, err := upq.path(ctx)
		if err != nil {
			return err
		}
		upq.sql = prev
	}
	return nil
}

func (upq *UserProviderQuery) sqlAll(ctx context.Context) ([]*UserProvider, error) {
	var (
		nodes = []*UserProvider{}
		_spec = upq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &UserProvider{config: upq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, upq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (upq *UserProviderQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := upq.querySpec()
	return sqlgraph.CountNodes(ctx, upq.driver, _spec)
}

func (upq *UserProviderQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := upq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (upq *UserProviderQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   userprovider.Table,
			Columns: userprovider.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: userprovider.FieldID,
			},
		},
		From:   upq.sql,
		Unique: true,
	}
	if unique := upq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := upq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userprovider.FieldID)
		for i := range fields {
			if fields[i] != userprovider.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := upq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := upq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := upq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := upq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (upq *UserProviderQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(upq.driver.Dialect())
	t1 := builder.Table(userprovider.Table)
	columns := upq.fields
	if len(columns) == 0 {
		columns = userprovider.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if upq.sql != nil {
		selector = upq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range upq.predicates {
		p(selector)
	}
	for _, p := range upq.order {
		p(selector)
	}
	if offset := upq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := upq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserProviderGroupBy is the group-by builder for UserProvider entities.
type UserProviderGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (upgb *UserProviderGroupBy) Aggregate(fns ...AggregateFunc) *UserProviderGroupBy {
	upgb.fns = append(upgb.fns, fns...)
	return upgb
}

// Scan applies the group-by query and scans the result into the given value.
func (upgb *UserProviderGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := upgb.path(ctx)
	if err != nil {
		return err
	}
	upgb.sql = query
	return upgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (upgb *UserProviderGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := upgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (upgb *UserProviderGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(upgb.fields) > 1 {
		return nil, errors.New("ent: UserProviderGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := upgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (upgb *UserProviderGroupBy) StringsX(ctx context.Context) []string {
	v, err := upgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (upgb *UserProviderGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = upgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userprovider.Label}
	default:
		err = fmt.Errorf("ent: UserProviderGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (upgb *UserProviderGroupBy) StringX(ctx context.Context) string {
	v, err := upgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (upgb *UserProviderGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(upgb.fields) > 1 {
		return nil, errors.New("ent: UserProviderGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := upgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (upgb *UserProviderGroupBy) IntsX(ctx context.Context) []int {
	v, err := upgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (upgb *UserProviderGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = upgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userprovider.Label}
	default:
		err = fmt.Errorf("ent: UserProviderGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (upgb *UserProviderGroupBy) IntX(ctx context.Context) int {
	v, err := upgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (upgb *UserProviderGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(upgb.fields) > 1 {
		return nil, errors.New("ent: UserProviderGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := upgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (upgb *UserProviderGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := upgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (upgb *UserProviderGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = upgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userprovider.Label}
	default:
		err = fmt.Errorf("ent: UserProviderGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (upgb *UserProviderGroupBy) Float64X(ctx context.Context) float64 {
	v, err := upgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (upgb *UserProviderGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(upgb.fields) > 1 {
		return nil, errors.New("ent: UserProviderGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := upgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (upgb *UserProviderGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := upgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (upgb *UserProviderGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = upgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userprovider.Label}
	default:
		err = fmt.Errorf("ent: UserProviderGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (upgb *UserProviderGroupBy) BoolX(ctx context.Context) bool {
	v, err := upgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (upgb *UserProviderGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range upgb.fields {
		if !userprovider.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := upgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := upgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (upgb *UserProviderGroupBy) sqlQuery() *sql.Selector {
	selector := upgb.sql.Select()
	aggregation := make([]string, 0, len(upgb.fns))
	for _, fn := range upgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(upgb.fields)+len(upgb.fns))
		for _, f := range upgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(upgb.fields...)...)
}

// UserProviderSelect is the builder for selecting fields of UserProvider entities.
type UserProviderSelect struct {
	*UserProviderQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ups *UserProviderSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ups.prepareQuery(ctx); err != nil {
		return err
	}
	ups.sql = ups.UserProviderQuery.sqlQuery(ctx)
	return ups.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ups *UserProviderSelect) ScanX(ctx context.Context, v interface{}) {
	if err := ups.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (ups *UserProviderSelect) Strings(ctx context.Context) ([]string, error) {
	if len(ups.fields) > 1 {
		return nil, errors.New("ent: UserProviderSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ups.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ups *UserProviderSelect) StringsX(ctx context.Context) []string {
	v, err := ups.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (ups *UserProviderSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ups.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userprovider.Label}
	default:
		err = fmt.Errorf("ent: UserProviderSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ups *UserProviderSelect) StringX(ctx context.Context) string {
	v, err := ups.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (ups *UserProviderSelect) Ints(ctx context.Context) ([]int, error) {
	if len(ups.fields) > 1 {
		return nil, errors.New("ent: UserProviderSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ups.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ups *UserProviderSelect) IntsX(ctx context.Context) []int {
	v, err := ups.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (ups *UserProviderSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ups.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userprovider.Label}
	default:
		err = fmt.Errorf("ent: UserProviderSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ups *UserProviderSelect) IntX(ctx context.Context) int {
	v, err := ups.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (ups *UserProviderSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ups.fields) > 1 {
		return nil, errors.New("ent: UserProviderSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ups.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ups *UserProviderSelect) Float64sX(ctx context.Context) []float64 {
	v, err := ups.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (ups *UserProviderSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ups.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userprovider.Label}
	default:
		err = fmt.Errorf("ent: UserProviderSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ups *UserProviderSelect) Float64X(ctx context.Context) float64 {
	v, err := ups.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (ups *UserProviderSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ups.fields) > 1 {
		return nil, errors.New("ent: UserProviderSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ups.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ups *UserProviderSelect) BoolsX(ctx context.Context) []bool {
	v, err := ups.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (ups *UserProviderSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ups.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{userprovider.Label}
	default:
		err = fmt.Errorf("ent: UserProviderSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ups *UserProviderSelect) BoolX(ctx context.Context) bool {
	v, err := ups.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ups *UserProviderSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ups.sql.Query()
	if err := ups.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
