// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/user-management/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/user-management/pkg/db/ent/userfrozen"
)

// UserFrozenDelete is the builder for deleting a UserFrozen entity.
type UserFrozenDelete struct {
	config
	hooks    []Hook
	mutation *UserFrozenMutation
}

// Where appends a list predicates to the UserFrozenDelete builder.
func (ufd *UserFrozenDelete) Where(ps ...predicate.UserFrozen) *UserFrozenDelete {
	ufd.mutation.Where(ps...)
	return ufd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ufd *UserFrozenDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ufd.hooks) == 0 {
		affected, err = ufd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserFrozenMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ufd.mutation = mutation
			affected, err = ufd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ufd.hooks) - 1; i >= 0; i-- {
			if ufd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ufd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ufd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ufd *UserFrozenDelete) ExecX(ctx context.Context) int {
	n, err := ufd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ufd *UserFrozenDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: userfrozen.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: userfrozen.FieldID,
			},
		},
	}
	if ps := ufd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ufd.driver, _spec)
}

// UserFrozenDeleteOne is the builder for deleting a single UserFrozen entity.
type UserFrozenDeleteOne struct {
	ufd *UserFrozenDelete
}

// Exec executes the deletion query.
func (ufdo *UserFrozenDeleteOne) Exec(ctx context.Context) error {
	n, err := ufdo.ufd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userfrozen.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ufdo *UserFrozenDeleteOne) ExecX(ctx context.Context) {
	ufdo.ufd.ExecX(ctx)
}
